# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LearnRxSwift' do
	pod 'RxSwift'	
	pod 'RxCocoa'
	pod 'SDWebImage'
	pod 'IGListKit'
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LearnRxSwift

  target 'LearnRxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LearnRxSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
